/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculadoraMVP.Vista;

import CalculadoraMVP.Presentador.Presentador;
import javax.swing.JFrame;

/**
 *
 * @author eddyf
 */
public class VCalculadora extends javax.swing.JPanel implements IVCalculadora {
    private Presentador presentador;
    private JFrame frame = new JFrame("Calculadora MVP");
    private boolean reemplazar=false;
    private boolean coma=false;
    private boolean negative=false;
    
    public VCalculadora(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCalculadora = new javax.swing.JTextField();
        lblGuardado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPut7 = new javax.swing.JButton();
        btnPut8 = new javax.swing.JButton();
        btnPut9 = new javax.swing.JButton();
        btnPut4 = new javax.swing.JButton();
        btnPut5 = new javax.swing.JButton();
        btnPut6 = new javax.swing.JButton();
        btnNegativo = new javax.swing.JButton();
        btnPut0 = new javax.swing.JButton();
        btnPutComa = new javax.swing.JButton();
        btnPut1 = new javax.swing.JButton();
        btnPut2 = new javax.swing.JButton();
        btnPut3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnDividir = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();

        lblCalculadora.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblCalculadora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lblCalculadora.setText("0");
        lblCalculadora.setEnabled(false);

        lblGuardado.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblGuardado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblGuardado.setText("Elemento Guardado");
        lblGuardado.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCalculadora)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCalculadora)
                .addContainerGap())
        );

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCargar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 102));
        btnSalir.setText("AC");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPut7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut7.setText("7");
        btnPut7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut7ActionPerformed(evt);
            }
        });

        btnPut8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut8.setText("8");
        btnPut8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut8ActionPerformed(evt);
            }
        });

        btnPut9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut9.setText("9");
        btnPut9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut9ActionPerformed(evt);
            }
        });

        btnPut4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut4.setText("4");
        btnPut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut4ActionPerformed(evt);
            }
        });

        btnPut5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut5.setText("5");
        btnPut5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut5ActionPerformed(evt);
            }
        });

        btnPut6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut6.setText("6");
        btnPut6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut6ActionPerformed(evt);
            }
        });

        btnNegativo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnNegativo.setText("+/-");
        btnNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegativoActionPerformed(evt);
            }
        });

        btnPut0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut0.setText("0");
        btnPut0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut0ActionPerformed(evt);
            }
        });

        btnPutComa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPutComa.setText(",");
        btnPutComa.setEnabled(false);
        btnPutComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPutComaActionPerformed(evt);
            }
        });

        btnPut1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut1.setText("1");
        btnPut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut1ActionPerformed(evt);
            }
        });

        btnPut2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut2.setText("2");
        btnPut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut2ActionPerformed(evt);
            }
        });

        btnPut3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPut3.setText("3");
        btnPut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPut3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPut7)
                    .addComponent(btnPut4)
                    .addComponent(btnPut1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNegativo)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPut5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPut8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCargar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPut2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPut0, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPut9)
                    .addComponent(btnSalir)
                    .addComponent(btnPut6)
                    .addComponent(btnPut3)
                    .addComponent(btnPutComa))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCargar, btnGuardar, btnNegativo, btnPut0, btnPut1, btnPut2, btnPut3, btnPut4, btnPut5, btnPut6, btnPut7, btnPut8, btnPut9, btnPutComa, btnSalir});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSalir)
                    .addComponent(btnCargar)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPut9)
                    .addComponent(btnPut8)
                    .addComponent(btnPut7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPut6)
                    .addComponent(btnPut5)
                    .addComponent(btnPut4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPut3)
                    .addComponent(btnPut2)
                    .addComponent(btnPut1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPutComa)
                    .addComponent(btnPut0)
                    .addComponent(btnNegativo))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCargar, btnGuardar, btnNegativo, btnPut0, btnPut1, btnPut2, btnPut3, btnPut4, btnPut5, btnPut6, btnPut7, btnPut8, btnPut9, btnPutComa, btnSalir});

        btnDividir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnMultiplicar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnMultiplicar.setText("X");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnRestar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnRestar.setText("-");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        btnResultado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnResultado.setText("=");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        btnSumar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnSumar.setText("+");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDividir)
                .addGap(20, 20, 20))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMultiplicar)
                    .addComponent(btnRestar)
                    .addComponent(btnSumar)
                    .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDividir, btnMultiplicar, btnRestar, btnResultado, btnSumar});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSumar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDividir, btnMultiplicar, btnRestar, btnResultado, btnSumar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        presentador.guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnPut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut1ActionPerformed
        setNumero("1");
    }//GEN-LAST:event_btnPut1ActionPerformed

    private void btnPut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut2ActionPerformed
        setNumero("2");
    }//GEN-LAST:event_btnPut2ActionPerformed

    private void btnPut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut3ActionPerformed
        setNumero("3");
    }//GEN-LAST:event_btnPut3ActionPerformed

    private void btnPut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut4ActionPerformed
        setNumero("4");
    }//GEN-LAST:event_btnPut4ActionPerformed

    private void btnPut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut5ActionPerformed
        setNumero("5");
    }//GEN-LAST:event_btnPut5ActionPerformed

    private void btnPut6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut6ActionPerformed
        setNumero("6");
    }//GEN-LAST:event_btnPut6ActionPerformed

    private void btnPut7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut7ActionPerformed
        setNumero("7");
    }//GEN-LAST:event_btnPut7ActionPerformed

    private void btnPut8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut8ActionPerformed
        setNumero("8");
    }//GEN-LAST:event_btnPut8ActionPerformed

    private void btnPut9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut9ActionPerformed
        setNumero("9");
    }//GEN-LAST:event_btnPut9ActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        presentador.cargar();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        presentador.refresh();
        reemplazar=false;
        coma=false;
        negative=false;
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        presentador.calcular();
    }//GEN-LAST:event_btnResultadoActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        presentador.sumar();
        reemplazar=true;
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        presentador.restar();
        reemplazar=true;
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        presentador.multiplicar();
        reemplazar=true;
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        presentador.dividir();
        reemplazar=true;
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnPut0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPut0ActionPerformed
        setNumero("0");
    }//GEN-LAST:event_btnPut0ActionPerformed

    private void btnNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegativoActionPerformed
        double a = Double.valueOf(lblCalculadora.getText());
        a = -a;
        lblCalculadora.setText(String.valueOf(a));
    }//GEN-LAST:event_btnNegativoActionPerformed

    private void btnPutComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPutComaActionPerformed
        if (!coma) {
            setNumero(".");
            coma=true;
        }

    }//GEN-LAST:event_btnPutComaActionPerformed

    private void setNumero(String num){
        if (reemplazar) {
            this.lblCalculadora.setText(num);
        }else{
            coma=false;
            negative=false;
            if (!"0".equals(lblCalculadora.getText())) {
                this.lblCalculadora.setText(lblCalculadora.getText()+num);
            }else{
                this.lblCalculadora.setText(num);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnNegativo;
    private javax.swing.JButton btnPut0;
    private javax.swing.JButton btnPut1;
    private javax.swing.JButton btnPut2;
    private javax.swing.JButton btnPut3;
    private javax.swing.JButton btnPut4;
    private javax.swing.JButton btnPut5;
    private javax.swing.JButton btnPut6;
    private javax.swing.JButton btnPut7;
    private javax.swing.JButton btnPut8;
    private javax.swing.JButton btnPut9;
    private javax.swing.JButton btnPutComa;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lblCalculadora;
    private javax.swing.JTextField lblGuardado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPresentador(Presentador p){
       this.presentador=p;
    }

    @Override
    public void iniciar(){
        frame.setContentPane(this);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(570, 710);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    @Override
    public double getEntrada(){
        return Double.valueOf(lblCalculadora.getText());
    }

    @Override
    public void setSalida(String valorResultado, String valorGuardado){
        if (valorResultado!=null) {
            lblCalculadora.setText(valorResultado);
        }
        
        if (valorGuardado!=null) {
            lblGuardado.setText(valorGuardado);
        }
    }
}
